import pathlib

import abjad
import baca
import evans

import nyctivoe

maker = evans.SegmentMaker(
    instruments=nyctivoe.instruments,
    names=[
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
    ],
    abbreviations=[
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
    ],
    name_staves=False,
    fermata_measures=nyctivoe.fermata_measures_15,
    commands=[
        evans.MusicCommand(
            ("saxophone 1 voice", [0, 1]),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=5,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([_ + 6 for _ in [-20, -18, -16, -15, -16, -17]], [1, 2, -1, 3, -1]),
            evans.hairpin("p < f >", [7]),
            evans.slur([6]),
            # nyctivoe.zero_padding_glissando,
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", (2, 6)),
            nyctivoe.C_rhythm(
                rotation=0,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                # preamble=[-4],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-14], [1, 4, -3, 4, -3, 1, -3, 1]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [6, 7, 8]),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=4,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([_ + 6 for _ in [-20, -18, -16, -15, -16, -17]], [1, 2, -1, 3, -1]),
            evans.hairpin("p < f >", [7]),
            evans.slur([6]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", (9, 13)),
            nyctivoe.C_rhythm(
                rotation=-1,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-1],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-14], [1, 4, -3, 4, -3, 1, -3, 1]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", (13, 21)),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=5,
                extra_counts_rotation=-5,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([_ + 6 for _ in [-20, -18, -16, -15, -16, -17]], [1, 2, -1, 3, -1]),
            evans.hairpin("p < f >", [7]),
            evans.slur([6]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", (0, 4)),
            nyctivoe.C_rhythm(
                rotation=-2,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-2],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-19], [1, 4, -3, 4, -3, 1, -3, 1]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [4, 5]),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=4,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([_ + 4 for _ in [-20, -18, -16, -15, -16, -17]], [1, 2, -1, 3, -1]),
            evans.hairpin("p < f >", [7]),
            evans.slur([6]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", 6),
            nyctivoe.C_rhythm(
                rotation=-3,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-3],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-19], [1, 4, -3, 4, -3, 1, -3, 1]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [7, 8, 9]),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=3,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([_ + 6 for _ in [-20, -18, -16, -15, -16, -17]], [1, 2, -1, 3, -1]),
            evans.hairpin("p < f >", [7]),
            evans.slur([6]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", (10, 13)),
            nyctivoe.C_rhythm(
                rotation=-4,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                # preamble=[-4],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-19], [1, 4, -3, 4, -3, 1, -3, 1]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", (13, 21)),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=4,
                extra_counts_rotation=-4,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([_ + 6 for _ in [-20, -18, -16, -15, -16, -17]], [1, 2, -1, 3, -1]),
            evans.hairpin("p < f >", [7]),
            evans.slur([6]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [3, 4]),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=2,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [_ for _ in evans.Sequence([-5, -1, 2, 5]).mirror(False).rotate(10).random_walk(
                    length=100,
                    step_list=[1, 3, 2, 2],
                    random_seed=3,
                ).remove_repeats()]
            ),
            evans.hairpin(
                "p <| f > mf >",
                # counts=[7, 5, 3, 5],
                counts=[2, 5, 2, 6, 2, 7, 2, 6, 2, 5, 2, 5],
                cyclic=True,
                pitched=True,
                final_hairpin=False,
                remove_length_1_spanner_start=False,
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "gongs" 1', site="after"
            ),
            abjad.Clef("percussion"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [8, 9, 10]),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=2,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [_ for _ in evans.Sequence([-5, -1, 2, 5]).mirror(False).rotate(10).random_walk(
                    length=100,
                    step_list=[1, 3, 2, 2],
                    random_seed=3,
                ).remove_repeats()]
            ),
            evans.hairpin(
                "p <| f > mf >",
                # counts=[7, 5, 3, 5],
                counts=[2, 5, 2, 6, 2, 7, 2, 6, 2, 5, 2, 5],
                cyclic=True,
                pitched=True,
                final_hairpin=False,
                remove_length_1_spanner_start=False,
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "log drums" 1', site="after"
            ),
            abjad.Clef("percussion"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("percussion voice", (13, 21)),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=2,
                extra_counts_rotation=-2,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [_ for _ in evans.Sequence([-5, -1, 2, 5]).mirror(False).rotate(10).random_walk(
                    length=100,
                    step_list=[1, 3, 2, 2],
                    random_seed=3,
                ).remove_repeats()]
            ),
            evans.hairpin(
                "p <| f > mf >",
                # counts=[7, 5, 3, 5],
                counts=[2, 5, 2, 6, 2, 7, 2, 6, 2, 5, 2, 5],
                cyclic=True,
                pitched=True,
                final_hairpin=False,
                remove_length_1_spanner_start=False,
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "gongs" 1', site="after"
            ),
            evans.ArticulationHandler(
                ["tremolo"],
                articulation_boolean_vector=[1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
            ),
            abjad.Clef("percussion"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("viola voice", (0, 2)),
            nyctivoe.C_rhythm(
                rotation=-5,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-1],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-12], [1, 4, -3, 4, -3]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("petrucci-c3"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("string 1 voice", [2, 3]),
            nyctivoe.D_rhythm(
                stage=4,
                extra_counts_rotation=-8,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [
                    float(abjad.Clef("percussion").to_pitch(abjad.StaffPosition(_)))
                    for _ in [
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        1,
                        -3,
                        -1,
                        1,
                        -3,
                        1,
                        3,
                        -1,
                        1,
                    ]
                ]
            ),
            abjad.Clef("percussion"),
            abjad.LilyPondLiteral(
                r"\revert Staff.StaffSymbol.line-positions", site="before"
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("viola voice", [2, 3]),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=8,
                extra_counts_rotation=-8,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([[-12, -5, 2, 9], [_ + 24 for _ in [-12, -5, 2, 9]]]),
            nyctivoe.zero_padding_glissando,
            abjad.Clef("petrucci-c3"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("viola voice", (4, 9)),
            nyctivoe.C_rhythm(
                rotation=-6,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-2],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-12], [1, 4, -3, 4, -3]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("petrucci-c3"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("string 1 voice", [9, 10, 11]),
            nyctivoe.D_rhythm(
                stage=4,
                extra_counts_rotation=-9,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [
                    float(abjad.Clef("percussion").to_pitch(abjad.StaffPosition(_)))
                    for _ in [
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        1,
                        -3,
                        -1,
                        1,
                        -3,
                        1,
                        3,
                        -1,
                        1,
                    ]
                ]
            ),
            abjad.Clef("percussion"),
            abjad.LilyPondLiteral(
                r"\revert Staff.StaffSymbol.line-positions", site="before"
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("viola voice", [9, 10, 11]),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=9,
                extra_counts_rotation=-9,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([[-12, -5, 2, 9], [_ + 24 for _ in [-12, -5, 2, 9]]]),
            nyctivoe.zero_padding_glissando,
            abjad.Clef("petrucci-c3"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("viola voice", 12),
            nyctivoe.C_rhythm(
                rotation=-7,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-3],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-12], [1, 4, -3, 4, -3]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("petrucci-c3"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("viola voice", (13, 21)),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=10,
                extra_counts_rotation=-10,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([-12, 12]),
            nyctivoe.zero_padding_glissando,
            evans.hairpin(
                "ff > p",
                counts=[85],
                # cyclic=True,
                pitched=True,
                final_hairpin=False,
                remove_length_1_spanner_start=False,
            ),
            abjad.Clef("petrucci-c3"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", 0),
            nyctivoe.C_rhythm(
                rotation=-8,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                # preamble=[-4],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-20], [1, 4, -3, 4, -3]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("string 2 voice", [1, 2]),
            nyctivoe.D_rhythm(
                stage=4,
                extra_counts_rotation=-11,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [
                    float(abjad.Clef("percussion").to_pitch(abjad.StaffPosition(_)))
                    for _ in [
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        1,
                        -3,
                        -1,
                        1,
                        -3,
                        1,
                        3,
                        -1,
                        1,
                    ]
                ]
            ),
            abjad.Clef("percussion"),
            abjad.LilyPondLiteral(
                r"\revert Staff.StaffSymbol.line-positions", site="before"
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", [1, 2]),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=11,
                extra_counts_rotation=-11,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([[_ - 12 for _ in [-12, -5, 2, 9]], [_ + 12 for _ in [-12, -5, 2, 9]]]),
            nyctivoe.zero_padding_glissando,
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", [3, 4]),
            nyctivoe.C_rhythm(
                rotation=-9,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-1],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-20], [1, 4, -3, 4, -3]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("string 2 voice", [5, 6, 7]),
            nyctivoe.D_rhythm(
                stage=4,
                extra_counts_rotation=-12,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler(
                [
                    float(abjad.Clef("percussion").to_pitch(abjad.StaffPosition(_)))
                    for _ in [
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        -3,
                        -1,
                        1,
                        3,
                        1,
                        -1,
                        1,
                        -3,
                        -1,
                        1,
                        -3,
                        1,
                        3,
                        -1,
                        1,
                    ]
                ]
            ),
            abjad.Clef("percussion"),
            abjad.LilyPondLiteral(
                r"\revert Staff.StaffSymbol.line-positions", site="before"
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", [5, 6, 7]),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=12,
                extra_counts_rotation=-12,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([[_ - 12 for _ in [-12, -5, 2, 9]], [_ + 12 for _ in [-12, -5, 2, 9]]]),
            nyctivoe.zero_padding_glissando,
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", (8, 13)),
            nyctivoe.C_rhythm(
                rotation=-10,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-2],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=4,
            ),
            evans.loop([-20], [1, 4, -3, 4, -3]),
            nyctivoe.upward_gliss,
            lambda _: baca.hairpin(_, "mp < ff", pieces=lambda x: abjad.select.runs(x)),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("cello voice", (13, 21)),
            nyctivoe.D_rhythm(
                stage=2,
                numerator_rotation=13,
                extra_counts_rotation=-13,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.PitchHandler([-24, 0]),
            nyctivoe.zero_padding_glissando,
            evans.hairpin(
                "ff > p",
                counts=[85],
                # cyclic=True,
                pitched=True,
                final_hairpin=False,
                remove_length_1_spanner_start=False,
            ),
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.call(
            "score",
            evans.SegmentMaker.beam_score_without_splitting,
            lambda _: abjad.select.components(_, abjad.Score),
        ),
        evans.attach(
            "Global Context",
            nyctivoe.lib.mark_120,
            lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "Global Context",
            nyctivoe.lib.met_120,
            lambda _: abjad.select.leaf(_, 0),
        ),
        # evans.attach(
        #     "Global Context",
        #     abjad.LilyPondLiteral(r'\sectionLabel \markup \underline "Segment 15"', site="before"),
        #     evans.select_measures([0], leaf=0),
        # ),
    ],
    score_template=nyctivoe.score,
    transpose_from_sounding_pitch=True,
    time_signatures=nyctivoe.signatures_15,
    clef_handlers=[None, None, None, None, None, None, None, None, None],
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        "abjad.ily",
        "../../build/segment_stylesheet.ily",
    ],
    segment_name="15",
    current_directory=pathlib.Path(__file__).parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=True,
    barline="||",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    mm_rests=False,
    extra_rewrite=False,  # should default to false but defaults to true
    print_clock_time=True,
    color_out_of_range=False,
)

maker.build_segment()
