import pathlib

import abjad
import baca
import evans

import nyctivoe

maker = evans.SegmentMaker(
    instruments=nyctivoe.instruments,
    names=[
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
    ],
    abbreviations=[
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
    ],
    name_staves=False,
    fermata_measures=nyctivoe.fermata_measures_14,
    commands=[
        evans.MusicCommand(
            ("saxophone 1 voice", [0, 1, 2]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[2],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([9, 10.5, 12, 9.5, 8.5, 7, 5.5, 7.5, 3], [1, 3, -2, 1, 2, 1, -2]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", (3, 6)),
            nyctivoe.C_rhythm(
                rotation=0,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                # preamble=[-4],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [6, 7]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["aqs"]),
            abjad.Dynamic("mp"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [8, 9, 10, 11]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[2],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([10.5, 12, 9.5, 8.5, 7, 5.5, 7.5, 3, 9], [1, 3, -2, 1, 2, 1, -2]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [12, 13]),
            nyctivoe.C_rhythm(
                rotation=-1,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-1],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [14, 15]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[2],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([12, 9.5, 8.5, 7, 5.5, 7.5, 3, 9, 10.5], [1, 3, -2, 1, 2, 1, -2]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", 16),
            nyctivoe.C_rhythm(
                rotation=-2,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-2],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", 17),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["aqs"]),
            abjad.Dynamic("mp"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [18]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[2],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([9.5, 8.5, 7, 5.5, 7.5, 3, 9, 10.5, 12], [1, 3, -2, 1, 2, 1, -2]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [0, 1, 2]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([9, 3, 10.5, 7.5, 12, 5.5, 9.5, 7, 8.5], [1, -2, 3, 1, -2, 1, 2,]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", 3),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=-3,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([-20, -18, -16, -15, -16, -17], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=7.25,
                id=1,
            ),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", (4, 7)),
            nyctivoe.C_rhythm(
                rotation=-3,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-3],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", 7),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=-3,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([-20, -18, -16, -15, -16, -17], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=7.25,
                id=1,
            ),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [8, 9, 10, 11]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([8.5, 9, 3, 10.5, 7.5, 12, 5.5, 9.5, 7], [1, -2, 3, 1, -2, 1, 2,]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", 12),
            nyctivoe.D_rhythm(
                stage=1,
                extra_counts_rotation=-3,
                preprocessor=evans.make_preprocessor(quarters=True),
            ),
            evans.loop([-20, -18, -16, -15, -16, -17], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=7.25,
                id=1,
            ),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("treble"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", 13),
            nyctivoe.C_rhythm(
                rotation=-4,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                # preamble=[-4],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [14, 15]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([7, 8.5, 9, 3, 10.5, 7.5, 12, 5.5, 9.5], [1, -2, 3, 1, -2, 1, 2,]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [16, 17]),
            nyctivoe.C_rhythm(
                rotation=-5,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-1],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [18]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.loop([9.5, 7, 8.5, 9, 3, 10.5, 7.5, 12, 5.5], [1, -2, 3, 1, -2, 1, 2,]),
            lambda _: baca.register(abjad.select.leaves(_), -12),
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("treble"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [0, 1, 2]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[3],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.PitchHandler(["a,", "c,"]),
            abjad.glissando,
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 5", site="before"),
            abjad.LilyPondLiteral(r'\boxed-markup "timpani + cymbal" 1', site="after"),
            evans.ArticulationHandler(["tremolo"]),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [3, 4]),
            evans.make_tied_notes(rewrite=False),
            abjad.Dynamic("mp"),
            abjad.Clef("percussion"),
            abjad.LilyPondLiteral(r"\staff-line-count 1", site="before"),
            abjad.LilyPondLiteral(r'\boxed-markup "tam tam + superball" 1', site="after"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [8, 9, 10, 11]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[3],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.PitchHandler(["a,", "c,"]),
            abjad.glissando,
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 5", site="before"),
            abjad.LilyPondLiteral(r'\boxed-markup "timpani + cymbal" 1', site="after"),
            evans.ArticulationHandler(["tremolo"]),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [12, 13]),
            evans.make_tied_notes(rewrite=False),
            abjad.Dynamic("mp"),
            abjad.LilyPondLiteral(r"\staff-line-count 1", site="before"),
            abjad.LilyPondLiteral(r'\boxed-markup "bass drum + superball" 1', site="after"),
            abjad.Clef("percussion"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [14, 15]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[3],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.PitchHandler(["a,", "c,"]),
            abjad.glissando,
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 5", site="before"),
            abjad.LilyPondLiteral(r'\boxed-markup "timpani + cymbal" 1', site="after"),
            evans.ArticulationHandler(["tremolo"]),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [18]),
            nyctivoe.B_rhythm(
                stage=1,
                numerators=[7, 8, 6],
                # rest_indices=[0, 2, 5, 7, 12, 13, 14, 20, 22, 30],
                # rest_period=35,
                extra_counts=[3],
                preprocessor=evans.make_preprocessor(
                    # sum=True,
                    quarters=True,  # fuse_counts=[2, 1, 2, 2, 1, 1, 1]
                ),
                rewrite=True,
            ),
            evans.PitchHandler(["a,", "c,"]),
            abjad.glissando,
            evans.Attachment(
                abjad.Dynamic("f"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.StartHairpin(">"),
                selector=lambda _: abjad.select.leaf(_, 0, pitched=True),
            ),
            evans.Attachment(
                abjad.Dynamic("pp"),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("viola voice", [0, 1, 2]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["bf", "g'"]]),
            abjad.Dynamic("mf"),
            abjad.Clef("petrucci-c3"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("viola voice", (3, 6)),
            nyctivoe.C_rhythm(
                rotation=-6,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-2],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("petrucci-c3"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("viola voice", [6, 7]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["eqs'"]),
            abjad.Dynamic("mp"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("viola voice", [8, 9, 10, 11]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["bf", "g'"]]),
            abjad.Dynamic("mf"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("viola voice", [12, 13]),
            nyctivoe.C_rhythm(
                rotation=-7,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-3],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("petrucci-c3"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("viola voice", [14, 15]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["bf", "g'"]]),
            abjad.Dynamic("mf"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("viola voice", 16),
            nyctivoe.C_rhythm(
                rotation=-8,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                # preamble=[-4],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("petrucci-c3"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("viola voice", 17),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["eqs'"]),
            abjad.Dynamic("mp"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("viola voice", 18),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["bf", "g'"]]),
            abjad.Dynamic("mf"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("cello voice", [0, 1, 2]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["cs,", "b,"]]),
            abjad.Dynamic("mf"),
            abjad.Clef("bass"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("cello voice", 3),
            evans.talea(
                [1],
                16,
                extra_counts=[0, 0, 2, 1, 0, 3, 0, 2],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=-1,
            ),
            evans.loop([-11, -10, -9, -8, -7, -6], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=3.25,
                id=1,
            ),
            evans.text_span([r"norm.", r"scr."], "=>", padding=5.25, id=2),
            evans.text_span([r"1/2 clt."], "=|", padding=7.25, id=3),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", (4, 7)),
            nyctivoe.C_rhythm(
                rotation=-9,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-1],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("cello voice", 7),
            evans.talea(
                [1],
                16,
                extra_counts=[0, 0, 2, 1, 0, 3, 0, 2],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=-1,
            ),
            evans.loop([-11, -10, -9, -8, -7, -6], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=3.25,
                id=1,
            ),
            evans.text_span([r"norm.", r"scr."], "=>", padding=5.25, id=2),
            evans.text_span([r"1/2 clt."], "=|", padding=7.25, id=3),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", [8, 9, 10, 11]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["cs,", "b,"]]),
            abjad.Dynamic("mf"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("cello voice", 12),
            evans.talea(
                [1],
                16,
                extra_counts=[0, 0, 2, 1, 0, 3, 0, 2],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=-1,
            ),
            evans.loop([-11, -10, -9, -8, -7, -6], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=3.25,
                id=1,
            ),
            evans.text_span([r"norm.", r"scr."], "=>", padding=5.25, id=2),
            evans.text_span([r"1/2 clt."], "=|", padding=7.25, id=3),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", 13),
            nyctivoe.C_rhythm(
                rotation=-10,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-2],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("cello voice", [14, 15]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["cs,", "b,"]]),
            abjad.Dynamic("mf"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("cello voice", [16, 17]),
            nyctivoe.C_rhythm(
                rotation=-11,
                extra_counts=[0, 0, 1, 2, 3, 1, 0, 3, 2],
                preamble=[-3],
                preprocessor=evans.make_preprocessor(quarters=True),
                stage=3,
            ),
            evans.loop([-12], [1, 3, -2, 1, 2, 1, -2]),
            nyctivoe.upward_gliss,
            nyctivoe.swells,
            evans.ArticulationHandler(
                articulation_list=["tremolo"],
                articulation_boolean_vector=[
                    0,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1,
                ],
                vector_forget=False,
                forget=False,
            ),
            evans.Attachment(
                abjad.Clef("bass"),
                selector=lambda _: abjad.select.leaf(_, 0),
            ),
            # nyctivoe.C_color,
        ),
        evans.MusicCommand(
            ("cello voice", 18),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["cs,", "b,"]]),
            abjad.Dynamic("mf"),
            # nyctivoe.E_color,
        ),
        evans.call(
            "score",
            evans.SegmentMaker.beam_score_without_splitting,
            lambda _: abjad.select.components(_, abjad.Score),
        ),
        evans.attach(
            "Global Context",
            nyctivoe.lib.mark_92,
            lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "Global Context",
            nyctivoe.lib.met_92,
            lambda _: abjad.select.leaf(_, 0),
        ),
        # evans.attach(
        #     "Global Context",
        #     abjad.LilyPondLiteral(r'\sectionLabel \markup \underline "Segment 14"', site="before"),
        #     evans.select_measures([0], leaf=0),
        # ),
    ],
    score_template=nyctivoe.score,
    transpose_from_sounding_pitch=True,
    time_signatures=nyctivoe.signatures_14,
    clef_handlers=[None, None, None, None, None, None, None, None, None],
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        "abjad.ily",
        "../../build/segment_stylesheet.ily",
    ],
    segment_name="14",
    current_directory=pathlib.Path(__file__).parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=True,
    barline="||",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    mm_rests=False,
    extra_rewrite=False,  # should default to false but defaults to true
    print_clock_time=True,
    color_out_of_range=False,
)

maker.build_segment()
