import pathlib

import abjad
import baca
import evans

import nyctivoe

maker = evans.SegmentMaker(
    instruments=nyctivoe.instruments,
    names=[
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
    ],
    abbreviations=[
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
        '" "',
    ],
    name_staves=False,
    fermata_measures=nyctivoe.fermata_measures_10,
    commands=[
        evans.MusicCommand(
            ("saxophone 1 voice", [0, 1]),
            evans.make_tied_notes(rewrite=False),
            nyctivoe.tenor_multiphonics,
            nyctivoe.tenor_fingerings,
            nyctivoe.tenor_dynamics,
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [2, 3, 4]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1],
                rest_period=2,
                extra_counts=[0, 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "f",
                    "d",
                    "cqs",
                    "aqs",
                    "a",
                    "f",
                    "eqs",
                    "cqs'",
                    "c'",
                    "a",
                    "gqs",
                    "eqs'",
                    "e'",
                    "c'",
                    "bqs",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"1/2 air tone"], "=|", padding=5, id=1),
            abjad.Clef("treble"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [5, 6, 7]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["bf"]),
            abjad.Dynamic("sfp"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("saxophone 1 voice", [8, 9, 10, 11, 12, 13]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1, 4],
                rest_period=7,
                extra_counts=[0, 1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "f",
                    "d",
                    "cqs",
                    "aqs",
                    "a",
                    "f",
                    "eqs",
                    "cqs'",
                    "c'",
                    "a",
                    "gqs",
                    "eqs'",
                    "e'",
                    "c'",
                    "bqs",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"1/2 air tone"], "=|", padding=5, id=1),
            abjad.Clef("treble"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [0, 1]),
            evans.make_tied_notes(rewrite=False),
            nyctivoe.baritone_multiphonics,
            nyctivoe.baritone_fingerings,
            nyctivoe.baritone_dynamics,
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [2, 3, 4, 5]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[4, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1],
                rest_period=2,
                extra_counts=[1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "bqs",
                    "f",
                    "c'",
                    "d",
                    "e'",
                    "cqs",
                    "eqs'",
                    "aqs",
                    "gqs",
                    "a",
                    "f",
                    "c'",
                    "eqs",
                    "cqs'",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"1/2 air tone"], "=|", padding=5, id=1),
            abjad.Clef("treble"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [6, 7]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["b,"]),
            abjad.Dynamic("sfp"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("saxophone 2 voice", [8, 9, 10, 11, 12, 13]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[4, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1, 4],
                rest_period=7,
                extra_counts=[1, 0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "bqs",
                    "f",
                    "c'",
                    "d",
                    "e'",
                    "cqs",
                    "eqs'",
                    "aqs",
                    "gqs",
                    "a",
                    "f",
                    "c'",
                    "eqs",
                    "cqs'",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"1/2 air tone"], "=|", padding=5, id=1),
            abjad.Clef("treble"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [0, 1]),
            nyctivoe.A_rhythm(
                stage=1,
                numerators=[10, 7, 8, 13, 8, 6, 1, -1, 3],
                extra_counts=[1],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=None,
            ),
            evans.PitchHandler(["c,", "a,"]),
            abjad.glissando,
            abjad.Clef("bass"),
            abjad.LilyPondLiteral(r"\staff-line-count 5", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "timpani + cymbal" 1', site="after"
            ),
            evans.ArticulationHandler(["tremolo"]),
            abjad.Dynamic("mf"),
            # nyctivoe.A_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [2, 3, 4, 5]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[0],
                rest_period=2,
                extra_counts=[0, 1, 0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [_ for _ in evans.Sequence([-5, -1, 2, 5]).mirror(False).rotate(10).random_walk(
                    length=100,
                    step_list=[1, 3, 2, 2],
                    random_seed=3,
                ).remove_repeats()]
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "gongs" 1', site="after"
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            abjad.Clef("percussion"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [6, 7, 8]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["c,"]),
            evans.Attachment(
                abjad.BendAfter(3),
                selector=lambda _: abjad.select.leaf(_, -1, pitched=True),
            ),
            abjad.Clef("bass"),
            abjad.LilyPondLiteral(r"\staff-line-count 5", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "timpani + cymbal" 1', site="after"
            ),
            evans.ArticulationHandler(["tremolo"]),
            abjad.Dynamic("sfp"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("percussion voice", [9, 10, 11, 12, 13]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1, 4],
                rest_period=7,
                extra_counts=[1, 0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [_ for _ in evans.Sequence([-5, -1, 2, 5]).mirror(False).rotate(10).random_walk(
                    length=100,
                    step_list=[1, 3, 2, 2],
                    random_seed=3,
                ).remove_repeats()]
            ),
            abjad.LilyPondLiteral(r"\staff-line-count 4", site="before"),
            abjad.LilyPondLiteral(
                r'\boxed-markup "gongs" 1', site="after"
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            abjad.Clef("percussion"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("viola voice", [0, 1]),
            evans.talea(
                [1],
                16,
                extra_counts=[2, 0, 0, 2, 1, 0, 3, 0],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=-1,
            ),
            evans.loop([-1, 0, 1, 2, 0.5], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([5]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [5],
                padding=3.25,
                id=1,
            ),
            evans.text_span([r"norm.", r"scr."], "=>", padding=5.25, id=2),
            evans.text_span([r"1/2 clt."], "=|", padding=7.25, id=3),
            evans.hairpin("p < f >", [6]),
            abjad.Clef("petrucci-c3"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("viola voice", [2, 3, 4]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[4, 4, 8, 8, 8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1],
                rest_period=2,
                extra_counts=[0, 1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "cqs'",
                    "bqs",
                    "eqs",
                    "f",
                    "c'",
                    "f",
                    "d",
                    "a",
                    "e'",
                    "a",
                    "cqs",
                    "gqs",
                    "eqs'",
                    "aqs",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"clt."], "=|", padding=5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=7, id=2),
            abjad.Clef("petrucci-c3"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("viola voice", [5, 6, 7]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler([["g'", "ef''"]]),
            abjad.Dynamic("sfp"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("viola voice", [8, 9, 10, 11, 12, 13]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1, 4],
                rest_period=7,
                extra_counts=[1, 2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "cqs'",
                    "bqs",
                    "eqs",
                    "f",
                    "c'",
                    "c'",
                    "f",
                    "d",
                    "a",
                    "e'",
                    "a",
                    "cqs",
                    "gqs",
                    "eqs'",
                    "aqs",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"clt."], "=|", padding=5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=7, id=2),
            abjad.Clef("petrucci-c3"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("cello voice", [0, 1]),
            evans.talea(
                [1],
                16,
                extra_counts=[0, 0, 2, 1, 0, 3, 0, 2],
                preprocessor=evans.make_preprocessor(quarters=True),
                rewrite=-1,
            ),
            evans.loop([-11, -10, -9, -8, -7, -6], [1, 2, -1, 3, -1]),
            abjad.LilyPondLiteral(r"\half-harmonic", site="before"),
            evans.Attachment(
                abjad.LilyPondLiteral(r"\revert-noteheads", site="after"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.slur([6]),
            evans.text_span(
                [r"\half-diamond-notehead-markup", r"\default-notehead-markup"],
                "=>",
                [6],
                padding=3.25,
                id=1,
            ),
            evans.text_span([r"norm.", r"scr."], "=>", padding=5.25, id=2),
            evans.text_span([r"1/2 clt."], "=|", padding=7.25, id=3),
            evans.hairpin("p < f >", [7]),
            abjad.Clef("bass"),
            # nyctivoe.D_color,
        ),
        evans.MusicCommand(
            ("cello voice", [2, 3, 4]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1],
                rest_period=2,
                extra_counts=[2, 1, 2, 0, 1, 2, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "aqs",
                    "cqs'",
                    "eqs'",
                    "bqs",
                    "gqs",
                    "eqs",
                    "cqs",
                    "f",
                    "a",
                    "c'",
                    "e'",
                    "c'",
                    "a",
                    "f",
                    "d",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"clt."], "=|", padding=5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=7, id=2),
            abjad.Clef("bass"),
            # nyctivoe.B_color,
        ),
        evans.MusicCommand(
            ("cello voice", [5, 6, 7, 8]),
            evans.make_tied_notes(rewrite=False),
            evans.PitchHandler(["e,"]),
            abjad.Dynamic("sfp"),
            # nyctivoe.E_color,
        ),
        evans.MusicCommand(
            ("cello voice", [9, 10, 11, 12, 13]),
            nyctivoe.B_rhythm(
                stage=2,
                run_denominators=[8, 16, 16, 16, 16, 16, 16, 16],
                rest_indices=[1, 4],
                rest_period=7,
                extra_counts=[1, 2, 0, 1, 3, 3, 2, 3, 1, 2],
                preprocessor=evans.make_preprocessor(
                    quarters=True, fuse_counts=[1, 1, 1, 2, 2, 1, 2]
                ),
                rewrite=False,
                treat_tuplets=True,
            ),
            evans.PitchHandler(
                [
                    "fqs",
                    "aqs",
                    "cqs'",
                    "eqs'",
                    "bqs",
                    "gqs",
                    "eqs",
                    "cqs",
                    "f",
                    "a",
                    "c'",
                    "e'",
                    "c'",
                    "a",
                    "f",
                    "d",
                ]
            ),
            abjad.Dynamic("p"),
            abjad.StartHairpin("<"),
            evans.Attachment(
                abjad.Dynamic("ff"),
                selector=lambda _: abjad.select.leaf(_, -1),
            ),
            evans.text_span([r"clt."], "=|", padding=5, id=1),
            evans.text_span([r"T", r"P"], "=>", padding=7, id=2),
            abjad.Clef("bass"),
            # nyctivoe.B_color,
        ),
        evans.call(
            "score",
            evans.SegmentMaker.beam_score_without_splitting,
            lambda _: abjad.select.components(_, abjad.Score),
        ),
        evans.attach(
            "Global Context",
            nyctivoe.lib.mark_75,
            lambda _: abjad.select.leaf(_, 0),
        ),
        evans.attach(
            "Global Context",
            nyctivoe.lib.met_75,
            lambda _: abjad.select.leaf(_, 0),
        ),
        # evans.attach(
        #     "Global Context",
        #     abjad.LilyPondLiteral(r'\sectionLabel \markup \underline "Segment 10"', site="before"),
        #     evans.select_measures([0], leaf=0),
        # ),
    ],
    score_template=nyctivoe.score,
    transpose_from_sounding_pitch=True,
    time_signatures=nyctivoe.signatures_10,
    clef_handlers=[None, None, None, None, None, None, None, None, None],
    tuplet_bracket_noteheads=False,
    add_final_grand_pause=False,
    score_includes=[
        "abjad.ily",
        "../../build/segment_stylesheet.ily",
    ],
    segment_name="10",
    current_directory=pathlib.Path(__file__).parent,
    cutaway=False,
    beam_pattern="meter",
    beam_rests=True,
    barline="||",
    rehearsal_mark="",
    fermata="scripts.ufermata",
    with_layout=True,
    mm_rests=False,
    extra_rewrite=False,  # should default to false but defaults to true
    print_clock_time=True,
    color_out_of_range=False,
)

maker.build_segment()
